"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['greenflare.py']
DATA_FILES = []
OPTIONS = {
	'iconfile': 'greenflare-icon-64x64.png',
	'plist': {
		'CFBundleName': 'Greenflare',
		'CFBundleIconFile': 'greenflare-icon-64x64.png',
		'CFBundleIdentifier': 'io.greenflare.crawler',
		'CFBundleShortVersionString': '0.75.2',
		'CFBundleDocumentTypes': [{'CFBundleTypeExtensions': ["gflaredb"], 'CFBundleTypeName': "Greenflare Crawl DB", 'CFBundleTypeRole': "Editor"}]
		},
	'argv_emulation': False
	}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)